[package]
name = "opcodes_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
revm = "19.4.0"
revm-interpreter = { version = "15.1.0", features = ["parse"] }

[dev-dependencies]
criterion = "0.3"
# opcodes_analysis = { path = "." } 
